name: cicd-strawman
services:
  ui:
    container_name: gradio-ui
    pull_policy: build
    build: .
    restart: always
    command: poetry run python ./src/cicd/ui/app.py
    volumes:
      - .:/code
    ports:
      - 7860:7860
