name: "Run Integration Tests"
description: "Run integration tests"
branding:
  icon: "code"
  color: "yellow"
inputs:
  environment:
    default: "dev"
    description: "Environment to deploy to"
  wait:
    default: "5"
    description: "Wait time in seconds before running tests"
runs:
  using: "composite"
  steps:
    - run: |
        echo "Deploying to preq..."
        sleep ${{inputs.wait}}
      name: Deploy to ${{inputs.environment}}
      shell: bash
