name: "Install Poetry"
description: "Install Poetry"
branding:
  icon: "code"
  color: "yellow"
runs:
  using: "composite"
  steps:
    - name: Configure Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Run pytest
      shell: bash
      run: |
        poetry install
        poetry run pytest --cov=src --cov-report term --cov-report xml

    - name: Upload code coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage.xml
