name: "CI/CD Strawman"

on:
  workflow_dispatch:
  push:


jobs:

  unit_tests:
    name: "Run unit tests"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/poetry
        name: Install Poetry

      - name: Run pytest
        run: |
          poetry install
          poetry run pytest --cov=src --cov-report term --cov-report xml

      - name: Upload code coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml


  code_scan_quality:
    name: "Code quality scan"
    runs-on: ubuntu-latest
    needs: [ unit_tests ]
    steps:

      - uses: actions/checkout@v4

      - name: Download code coverage report
        uses: actions/download-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml


      - name: Run code scan
        run: |
          echo "Press F to pay respects..."
          sleep 18


  code_scan_security:
    name: "Code security scan"
    runs-on: ubuntu-latest
    needs: [ unit_tests ]
    steps:

      - uses: actions/checkout@v4

      - name: Run code scan
        run: |
          echo "Your call is very important to us..."
          sleep 10

  deploy_dev:
    name: "Deploy to dev"
    runs-on: ubuntu-latest
    environment: dev
#    concurrency:
#      group: dev

    steps:
      - uses: actions/checkout@v4

      - run: |
          echo "Deploying to dev..."
          sleep 5
        name: Deploy to dev
        env:
          ENV: dev


  integration_tests_dev:
    name: "Integration tests in dev"
    runs-on: ubuntu-latest
    needs: [ deploy_dev ]
    environment: dev

    steps:
      - uses: actions/checkout@v4

      - name: Run pytest
        run: |
          echo "Running integration tests in dev..."
          sleep 13

  deploy_preq:
    name: "Deploy to preq"
    runs-on: ubuntu-latest
    environment: preq
    needs: [ integration_tests_dev, code_scan_quality, code_scan_security ]

    steps:
      - uses: actions/checkout@v4

      - run: |
          echo "Deploying to preq..."
          sleep 10
        name: Deploy to preq
        env:
          ENV: preq


  integration_tests_preq:
    name: "Integration tests in preq"
    runs-on: ubuntu-latest
    needs: [ deploy_preq ]

    steps:
      - uses: actions/checkout@v4

      - name: Run pytest
        run: |
          echo "Running integration tests in preq..."
          sleep 5

  deploy_prod:
    name: "Deploy to prod"
    runs-on: ubuntu-latest
    environment: prod
    needs: [ integration_tests_preq ]
#    concurrency:
#      group: dev

    steps:
      - uses: actions/checkout@v4

      - run: |
          echo "Deploying to prod..."
          sleep 20
        name: Deploy to prod
        env:
          ENV: prod
