name: "CI/CD Strawman"

on:
  workflow_dispatch:
  push:


jobs:

  #    _____  _____  ____  _____  ____
  #   |_   _|| ____|/ ___||_   _|/ ___|
  #     | |  |  _|  \___ \  | |  \___ \
  #     | |  | |___  ___) | | |   ___) |
  #     |_|  |_____||____/  |_|  |____/

  unit_tests:
    name: "Run unit tests"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/poetry
        name: Install Poetry

      - name: Run pytest
        run: |
          poetry install
          poetry run pytest --cov=src --cov-report term --cov-report xml

      - name: Upload code coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml




  #     ____  ___   ____   _____     ____    ____     _     _   _
  #    / ___|/ _ \ |  _ \ | ____|   / ___|  / ___|   / \   | \ | |
  #   | |   | | | || | | ||  _|     \___ \ | |      / _ \  |  \| |
  #   | |___| |_| || |_| || |___     ___) || |___  / ___ \ | |\  |
  #    \____|\___/ |____/ |_____|   |____/  \____|/_/   \_\|_| \_|

  code_scan:
    name: "Code Scan"
    runs-on: ubuntu-latest
    needs: [ unit_tests ]
    steps:

      - uses: actions/checkout@v4

      - name: Download code coverage report
        uses: actions/download-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml


      - name: Run code scan
        run: |
          echo "Scanning code..."


  deploy_dev:
    name: "Deploy to dev"
    runs-on: ubuntu-latest
    environment: dev
    concurrency:
      group: dev

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/poetry
        name: Install Poetry

      - run: echo "Deploying to dev..."
        name: Deploy to dev
        env:
          ENV: dev



  deploy_preq:
    name: "Deploy to preq"
    runs-on: ubuntu-latest
    environment: preq
    needs: [ code_scan, deploy_dev ]
    concurrency:
      group: dev

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/poetry
        name: Install Poetry

      - run: echo "Deploying to preq..."
        name: Deploy to preq
        env:
          ENV: preq

  deploy_prod:
    name: "Deploy to prod"
    runs-on: ubuntu-latest
    environment: prod
    needs: [ deploy_preq ]
    concurrency:
      group: dev
    if: false

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/poetry
        name: Install Poetry

      - run: echo "Deploying to prod..."
        name: Deploy to prod
        env:
          ENV: prod
